# Generated by Django 3.2.5 on 2022-07-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
