# Generated by Django 3.2.5 on 2022-07-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_basket', '0002_alter_receipt_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
