# Generated by Django 3.2.5 on 2022-07-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_basket', '0003_alter_receipt_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='code',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to='images/'),
        ),
    ]
