# Generated by Django 3.2.5 on 2022-07-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_basket', '0004_receipt_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='qrcodes/')),
            ],
        ),
    ]
